config/routes.rb
AML::Engine.routes.draw do
  root to: 'orders#index'
  delete 'reset_db' => 'application#reset_db'
  delete 'drop_clients' => 'application#drop_clients'
  delete 'drop_orders' => 'application#drop_orders'
  resources :agreements
  resources :notifications
  resources :notification_templates, only: %i[update create]
  resources :operators, except: %i[show destroy] do
    member do
      put :block
      put :unblock
    end
  end
  concern :archivable do
    member do
      delete :archive
      post :restore
    end
  end
  concern :processable do
    member do
      put :done
      put :start
      put :accept
      put :reject
      put :cancel
    end
  end
  resources :check_lists
  resources :statuses
  resources :document_group_to_statuses, only: %i[create destroy]
  resources :document_groups, except: %i[destroy] do
    concerns :archivable
    resources :document_kinds do
      concerns :archivable
      resources :document_kind_field_definitions do
        concerns :archivable
      end
    end
  end
  resources :clients, except: %i[edit destroy] do
    member do
      delete :reset
    end
  end
  resources :client_infos
  resources :orders do
    resources :checks, controller: :order_checks do
      member do
        put :accept
        put :reject
      end
    end
    resources :rejections, only: [:new, :create], controller: :order_rejections
    concerns :processable
  end
  resources :document_fields, only: %i[edit update]
  resources :order_documents, only: %i[show index edit update] do
    resources :rejections, only: [:new, :create], controller: :order_document_rejections
    member do
      put :accept
      put :reject
    end
  end
  resources :payment_card_orders do
    resources :rejections, only: [:new, :create], controller: :payment_card_order_rejections
    concerns :processable
  end
  resources :reject_reasons
  resources :payment_cards, only: :index
end

app/models/aml/agreement.rb
module AML
  class Agreement < ApplicationRecord
    include Archivable
    include Authority::Abilities

    translates :title, :details, touch: true
    globalize_accessors

    scope :ordered, -> { order :id }
  end
end

app/models/aml/check_list.rb
module AML
  class CheckList < ApplicationRecord
    include Archivable
    include Authority::Abilities

    scope :ordered, -> { order :position }

    has_many :aml_order_checks, class_name: 'AML::OrderCheck', dependent: :destroy, foreign_key: :aml_check_list_id

    validates :title, presence: true, uniqueness: { case_sensitive: false }

    after_create :add_to_open_orders

    def to_s
      title
    end

    private

    def add_to_open_orders
      AML::Order.open.find_each do |o|
        o.order_checks.create! aml_check_list: self
      end
    end

    # Перед архивацией
    #def remove_from_open_orders
      #AML::Order.open.find_each do |o|
        #o.order_checks.where(aml_check_list_id: id).destroy_all
      #end
    #end
  end
end

app/models/aml/client.rb
# frozen_string_literal: true

# TODO При изменении данных у Клиента создается новая заявка, в нее копируются все документы,
# но статус у них сбрасывается.

module AML
  class Client < ApplicationRecord
    extend Enumerize
    include Authority::Abilities

    scope :ordered, -> { order 'id desc' }

    belongs_to :current_order, class_name: 'AML::Order', dependent: :destroy, foreign_key: :aml_order_id, optional: true
    belongs_to :aml_accepted_order, class_name: 'AML::Order', dependent: :destroy, optional: true
    belongs_to :aml_status, class_name: 'AML::Status', optional: true

    has_one :aml_client_info, class_name: 'AML::ClientInfo', foreign_key: :aml_client_id

    has_many :aml_payment_cards, class_name: 'AML::PaymentCard', foreign_key: :aml_client_id
    has_many :orders, class_name: 'AML::Order', dependent: :destroy
    has_many :client_agreements, class_name: 'AML::ClientAgreement', foreign_key: :aml_client_id, dependent: :destroy
    has_many :payment_card_orders, class_name: 'AML::PaymentCardOrder', dependent: :destroy, foreign_key: :aml_client_id

    after_create :create_current_order!

    register_currency :eur
    monetize :total_income_amount_cents

    # Нужно для для сериализера
    alias_attribute :current_order_id, :aml_order_id

    enumerize :risk_category, in: %w(A B C)

    # TODO: Не может быть без имени если находится в статусе оформляется или принят/отклонен
    #
    # validates :name
    #
    # TODO При изменении клиента, в случае если он одобрен:
    #
    # 1) Создается новая заявка (create_current_order)
    # 2) workflow клиента сбрабсывается в none
    #

    def create_current_order! attrs = {}
      order = super attrs.merge client_id: id
      update_column :aml_order_id, order.id
    end

    # TODO Сохранять в таблице при before_update/create
    def all_agreements_accepted?
      client_agreements.count == AML::Agreement.alive.count
    end

    def notify(template_id, data = {})
      if email.present?
        AML::NotificationMailer.
          notify( email: email, template_id: template_id, data: data).
          deliver!
      else
        AML::NotificationMailer.logger.error "У клиента #{id} нет email-а"
      end
    end

    def notification_locale
      locale.presence || client_agreements.where.not(locale: nil).pluck(:locale).first
    end

    def reset_status!
      with_lock do
        update aml_status: nil, aml_accepted_order: nil, total_operations_count: 0, total_income_amount: Money.new(0, AML.currency)
        create_current_order!
      end
    end

    def name
      [first_name, surname, patronymic].compact.join ' '
    end

    def to_s
      "##{id} #{name}"
    end
  end
end

app/models/aml/client_agreement.rb
module AML
  class ClientAgreement < ApplicationRecord
    include Authority::Abilities

    belongs_to :aml_client, class_name: 'AML::Client'
    belongs_to :aml_agreement, class_name: 'AML::Agreement'

    validates :aml_agreement_id, presence: true, uniqueness: { scope: :aml_client_id }
  end
end

app/models/aml/client_document.rb
# frozen_string_literal: true

module AML
  # TODO: rename в OrderDocument
  class ClientDocument < ApplicationRecord
    extend Enumerize
    include Workflow
    include Authority::Abilities

    mount_uploader :image, FileUploader

    belongs_to :order, class_name: 'AML::Order', foreign_key: 'order_id', inverse_of: :order_documents
    belongs_to :document_kind, class_name: 'AML::DocumentKind', foreign_key: 'document_kind_id', inverse_of: :order_documents

    has_many :client_document_fields, class_name: 'AML::ClientDocumentField', dependent: :destroy
    has_many :document_kind_field_definitions, through: :document_kind, source: :definitions

    scope :ordered, -> { order 'id desc' }

    # validates :image, presence: true
    # validates :document_kind_id, uniqueness: { scope: :order_id }

    enumerize :workflow_state, in: %w[none pending processing accepted rejected], scope: true

    accepts_nested_attributes_for :client_document_fields, update_only: true

    workflow do
      state :pending do
        event :accept, transitions_to: :accepted
        event :reject, transitions_to: :rejected
      end

      state :accepted do
        event :reject, transitions_to: :rejected
      end

      state :rejected do
        event :accept, transitions_to: :accepted
      end
    end

    after_create :create_fields!

    def client_document_fields_attributes
      client_document_fields.map do |document_field|
        document_field.as_json only: %i[value document_kind_field_definition_id]
      end
    end

    def fields(reload = false)
      @fields = nil if reload
      @fields ||= client_document_fields.each_with_object({}) do |document_field, agg|
        agg[document_field.key] = document_field.value
      end.freeze
    end

    def fields=(_value)
      self.client_document_fields_attributes = fields.map do |_k, v|
        {
          definition: document_kind_field_definitions.find_by(key: key),
          client_document_id: id,
          value: v
        }
      end
    end

    private

    # TODO: устанавливать когда хоть что-нибудь появится, а может лучше вообще из API
    def order_loading
      order.load! if order.none? && order.complete?
    end

    def create_fields!
      document_kind_field_definitions.alive.pluck(:id).each do |definition_id|
        client_document_fields.create! definition_id: definition_id, client_document: self
      end
    end
  end
end

app/models/aml/client_document_field.rb
module AML
  # TODO Переименовать в DocumentField
  class ClientDocumentField < ApplicationRecord
    scope :ordered, -> { order 'id desc' }

    belongs_to :order_document, class_name: 'AML::OrderDocument',
                                 foreign_key: 'order_document_id',
                                 inverse_of: :client_document_fields

    belongs_to :definition, class_name: 'AML::DocumentKindFieldDefinition',
                            foreign_key: :document_kind_field_definition_id,
                            inverse_of: :client_document_fields

    validates :document_kind_field_definition_id, uniqueness: { scope: :order_document_id }

    alias_attribute :definition_id, :document_kind_field_definition_id

    delegate :title, :key, to: :definition
  end
end

app/models/aml/client_info.rb
module AML
  class ClientInfo < ApplicationRecord
    extend Enumerize
    include Authority::Abilities

    belongs_to :aml_client, class_name: 'AML::Client', foreign_key: :aml_client_id

    enumerize :gender, in: %w(male female)
  end
end

app/models/aml/document_field.rb
module AML
  # TODO Переименовать в DocumentField
  class DocumentField < ApplicationRecord
    include Authority::Abilities

    class ClosedOrderError < StandardError
      def message
        'Нельзя редактировать поле документа. Заявка закрыта для изменений.'
      end
    end

    scope :ordered, -> { order 'id desc' }

    belongs_to :order_document, class_name: 'AML::OrderDocument',
                                 foreign_key: 'order_document_id',
                                 inverse_of: :document_fields

    belongs_to :definition, class_name: 'AML::DocumentKindFieldDefinition',
                            foreign_key: :document_kind_field_definition_id,
                            inverse_of: :document_fields

    validates :document_kind_field_definition_id, uniqueness: { scope: :order_document_id }

    before_validation :validate_order_open!

    alias_attribute :definition_id, :document_kind_field_definition_id

    delegate :title, :key, to: :definition

    def validate_order_open!
      raise ClosedOrderError if order_document.order.is_locked? && value_changed?
    end
  end
end

app/models/aml/document_group.rb
module AML
  class DocumentGroup < ApplicationRecord
    include Archivable
    include Authority::Abilities

    translates :title, :details
    globalize_accessors

    has_many :aml_document_group_to_statuses, class_name: 'AML::DocumentGroupToStatus',
      inverse_of: :aml_document_group, foreign_key: :aml_document_group_id
    has_many :aml_statuses, through: :aml_document_group_to_statuses, class_name: 'AML::Status'
    has_many :document_kinds, class_name: 'AML::DocumentKind', dependent: :destroy, foreign_key: :aml_document_group_id

    scope :ordered, -> { order :position }

    validates :title, presence: true, uniqueness: { case_sensitive: false }

    before_create do
      if self.class.any?
        self.position ||= self.class.last.position + 1
      else
        self.position = 1
      end
    end
  end
end

app/models/aml/document_group_to_status.rb
module AML
  class DocumentGroupToStatus < ApplicationRecord
    include Authority::Abilities

    belongs_to :aml_document_group, class_name: 'AML::DocumentGroup'
    belongs_to :aml_status, class_name: 'AML::Status'
    has_many :document_kinds, through: :aml_document_group, class_name: 'AML::DocumentKind'
  end
end

app/models/aml/document_kind.rb
# frozen_string_literal: true

module AML
  class DocumentKind < ApplicationRecord
    include Archivable
    include Authority::Abilities

    translates :title, :details, :file_title
    globalize_accessors

    mount_uploader :file, DocumentKindFileUploader

    scope :ordered, -> { order 'position desc' }

    belongs_to :document_group, class_name: 'AML::DocumentGroup', foreign_key: :aml_document_group_id, inverse_of: :document_kinds
    has_many :definitions, class_name: 'AML::DocumentKindFieldDefinition', dependent: :destroy
    has_many :order_documents, class_name: 'AML::OrderDocument', dependent: :destroy

    validates :title, presence: true, uniqueness: { case_sensitive: false }
    validates :file_title, on: :update, presence: true, if: :file?

    # Поддержка для Serializer
    alias_attribute :document_group_id, :aml_document_group_id
  end
end

app/models/aml/document_kind_field_definition.rb
module AML
  # TODO Переименовать в FielDefinition
  #
  class DocumentKindFieldDefinition < ApplicationRecord
    include Archivable
    include Authority::Abilities

    translates :title
    globalize_accessors

    belongs_to :document_kind, class_name: 'AML::DocumentKind',
                               foreign_key: 'document_kind_id',
                               inverse_of: :definitions

    # Зачем эта ассоциация тут?
    has_many :document_fields, dependent: :destroy

    scope :ordered, -> { order 'position desc' }

    validates :title, presence: true, uniqueness: { scope: :document_kind_id }
    validates :key, presence: true, format: { with: /[a-z_]+/ }, uniqueness: { scope: :archived_at }
  end
end

app/models/aml/engine_version.rb
require 'semver'

module AML
  EngineVersion = SemVer.find
end

app/models/aml/notification.rb
module AML
  class Notification < ApplicationRecord
    extend Enumerize
    include Authority::Abilities

    has_many :aml_notification_templates, class_name: 'AML::NotificationTemplate', foreign_key: :aml_notification_id, dependent: :destroy

    validates :title, presence: true, uniqueness: { case_sensitive: false }
    validates :key, uniqueness: { case_sensitive: false }, allow_blank: true

    after_create :create_templates

    enumerize :key, in: %w(on_pending_notification on_accept_notification on_reject_notification)

    def to_s
      title
    end

    private

    def create_templates
      I18n.available_locales.each do |locale|
        aml_notification_templates.find_or_create_by!(locale: locale)
      end
    end
  end
end

app/models/aml/notification_template.rb
module AML
  class NotificationTemplate < ApplicationRecord
    include Authority::Abilities

    belongs_to :aml_notification, class_name: 'AML::Notification', foreign_key: :aml_notification_id

    validates :locale, presence: true, inclusion: { in: I18n.available_locales.map(&:to_s) }
  end
end

app/models/aml/operator.rb
require 'valid_email'
require 'enumerize'

module AML
  class Operator < ApplicationRecord
    extend Enumerize
    include Workflow
    include Authority::Abilities

    scope :ordered, -> { order 'id desc' }

    has_many :orders, class_name: 'AML::Order', dependent: :destroy
    has_many :payment_card_orders, class_name: 'AML::PaymentCardOrder', dependent: :destroy

    enum role: [:operator, :administrator]

    enumerize :workflow_state, in: %w[blocked unblocked], scope: true

    workflow do
      state :unblocked do
        event :block, transitions_to: :blocked
      end

      state :blocked do
        event :unblock, transitions_to: :unblocked
      end
    end

    # Удаляем методы определнные в workflow, чтобы они не конфликтовали
    # с authority
    remove_method :can_block?, :can_unblock?

    def notify(template_id, data = {})
      unless enable_notification
        AML::NotificationMailer.logger.debug "У оператора #{id} увеломдения запрещены, выходим из AML::Operator#notify"
        return
      end
      unless email.present?
        AML::NotificationMailer.logger.error "У оператора #{id} нет email-а"
        return
      end
      AML::NotificationMailer.
        notify( email: email, template_id: template_id, data: data).
        deliver!
    end

    def to_s
      "[#{id}] #{name}"
    end

    def to_partial_path
      'operator'
    end
  end
end

app/models/aml/order_check.rb
module AML
  class OrderCheck < ApplicationRecord
    include Workflow
    include Authority::Abilities

    belongs_to :aml_order, class_name: 'AML::Order'
    belongs_to :aml_check_list, class_name: 'AML::CheckList'

    workflow do
      state :none do
        event :accept, transitions_to: :accepted, if: :aml_order_processing?
        event :reject, transitions_to: :rejected, if: :aml_order_processing?
      end
      state :accepted do
        event :reject, transitions_to: :rejected, if: :aml_order_processing?
      end
      state :rejected do
        event :accept, transitions_to: :accepted, if: :aml_order_processing?
      end
    end

    delegate :processing?, to: :aml_order, prefix: true
  end
end

app/models/aml/payment_card.rb
module AML
  class PaymentCard < ApplicationRecord
    include Authority::Abilities

    scope :ordered, -> { order :id }

    belongs_to :aml_accepted_order, class_name: 'AML::PaymentCardOrder', foreign_key: :aml_payment_card_order_id, inverse_of: :aml_payment_card
    belongs_to :aml_client, class_name: 'AML::Client', foreign_key: :aml_client_id, inverse_of: :aml_payment_cards

    def masked_number
      # NOTE dup нужен, т.к. insert изменяет исходный объект
      "#{card_bin} **** #{card_suffix} #{card_brand} "
    end
  end
end

app/views/aml/payment_card_orders/_form.html.slim
= simple_form_for payment_card_order do |f|
  = f.input :aml_client_id, as: :hidden
  .row
    .col-md-3= f.input :card_brand
    .col-md-3= f.input :card_bin
    .col-md-3= f.input :card_suffix
  br
  = f.button :submit, 'Изменить', class: 'btn btn-success'

app/views/aml/payment_card_orders/_menu.slim
ul.nav.nav-tabs
  - if current_operator.administrator?
    = active_link_to payment_card_orders_path(workflow_state: :none), active: :exact, wrap_tag: :li do
      = title_with_counter 'Незаполненные', AML::PaymentCardOrder.with_none_state.count
  = active_link_to payment_card_orders_path(workflow_state: :pending), active: active_style_order(workflow_state), wrap_tag: :li do
    = title_with_counter 'Ожидают обработки', AML::PaymentCardOrder.with_pending_state.count
  = active_link_to payment_card_orders_path(workflow_state: :processing), active: :exact, wrap_tag: :li do
    = title_with_counter 'В обработке', AML::PaymentCardOrder.with_processing_state.count
  = active_link_to payment_card_orders_path(workflow_state: :accepted), active: :exact, wrap_tag: :li do
    = title_with_counter 'Принятые', AML::PaymentCardOrder.with_accepted_state.count
  = active_link_to payment_card_orders_path(workflow_state: :rejected), active: :exact, wrap_tag: :li do
    = title_with_counter 'Отклоненные', AML::PaymentCardOrder.with_rejected_state.count
  - if current_operator.administrator?
    = active_link_to payment_card_orders_path(workflow_state: :canceled), active: :exact, wrap_tag: :li do
      = title_with_counter 'Отмененные', AML::PaymentCardOrder.with_canceled_state.count

app/views/aml/payment_card_orders/_payment_card_order.html.slim
- payment_card_order_decorated = AML::PaymentCardOrderDecorator.decorate payment_card_order
tr
  td= payment_card_order.id
  td= humanized_time_in_current_time_zone payment_card_order.pending_at
  td= humanized_time_in_current_time_zone payment_card_order.operated_at
  td= payment_card_order_decorated.client_name
  td= payment_card_order_decorated.workflow_state
  td= payment_card_order.card_brand
  td= payment_card_order.card_bin
  td= payment_card_order.card_suffix
  td= image_tag(payment_card_order.image.url, style: 'height:auto;width:100%;') if payment_card_order.image.present?
  td= payment_card_order_decorated.operator
  td

    = render 'payment_card_order_actions', payment_card_order: payment_card_order
  td
    =< link_to 'Подробнее', payment_card_order_path(payment_card_order_decorated), class: 'btn btn-default'

app/views/aml/payment_card_orders/_payment_card_order_brief.slim
- payment_card_order_decorated = AML::PaymentCardOrderDecorator.decorate payment_card_order
hr
dl
  dt Заявка отправлена
  dd= humanized_time_in_current_time_zone payment_card_order.pending_at

  dt Клиент
  dd= payment_card_order_decorated.client_name

  dt Состояние
  dd= payment_card_order_decorated.workflow_state

  - if payment_card_order.rejected?
    = payment_card_order_decorated.reject_reason

  dt Card brand
  dd= payment_card_order.card_brand

  dt Card bin
  dd= payment_card_order.card_bin

  dt Card suffix
  dd= payment_card_order.card_suffix

  - if payment_card_order.current_state >= :processing
    dt Оператор
    dd= payment_card_order_decorated.operator

  - if payment_card_order.image.present?
    dt Изображение
    dd= image_tag(payment_card_order.image.url, style: 'height:auto;width:100%;')

app/views/aml/payment_card_orders/_payment_card_orders.slim
= paginate payment_card_orders
table.table.table-condensed.table-striped
  thead
    tr
      th= sort_link q, :id, 'Заявка'
      th= sort_link q, :pending_at, 'Отправлена'
      th= sort_link q, :operated_at, 'Обработана'
      th= sort_link q, :first_name, 'Клиент'
      th Состояние
      th Card brand:
      th Card bin:
      th Card suffix:
      th Изображение:
      th= sort_link q, :aml_operator_id,  'Оператор'
      th Действия
  tbody
    = render partial: 'aml/payment_card_orders/payment_card_order', collection: payment_card_orders
= paginate payment_card_orders

app/views/aml/payment_card_orders/_search.slim
= search_form_for @q, url: payment_card_orders_path do |f|
  = f.search_field :id_or_card_brand_cont
  = hidden_field_tag :workflow_state, workflow_state
  = f.submit 'Искать', class: 'btn btn-default'

app/views/aml/payment_card_orders/edit.html.slim
h3 Редактировать заявку на привязку карты
hr
= render 'form', payment_card_order: payment_card_order

app/views/aml/payment_card_orders/index.html.slim
= render 'search', workflow_state: workflow_state
= render 'menu', workflow_state: workflow_state

- if payment_card_orders.any?
  .m-t-md= render partial: 'payment_card_orders', locals: { payment_card_orders: payment_card_orders, q: q }

- else
  p.alert Заявки отсутствуют

app/views/aml/payment_card_orders/new.html.slim
h3 Новая заявка на привязку карты для клиента #{payment_card_order.aml_client_id}
hr
= render 'form', payment_card_order: payment_card_order

app/views/aml/payment_card_orders/show.html.slim
= link_to '&larr; список заявок'.html_safe, payment_card_orders_path(workflow_state: payment_card_order.workflow_state)
hr
.row
  .col-md-4
    h2.m-t-0 Заявка: #{payment_card_order.id}
= render 'payment_card_order_actions', payment_card_order: payment_card_order

- if payment_card_order.updatable_by?(current_operator)
  = simple_form_for payment_card_order, url: done_payment_card_order_path, method: :put do |f|
    = f.file_field :image
    br
    = f.button :submit, 'Загрузить', class: 'btn btn-success'

= render 'payment_card_order_brief', payment_card_order: payment_card_order